### ISSUE TITLE
Wallabag integration

### ISSUE THREAD

**Issue by wojtek1171** [JuanJakobo/PB-Read-offline#3]
Hi,
I know that this is not the best place for such a question but would it be much effort to create an app similar to this one but working with wallabag instance?
Best regards :)

**Comment by JuanJakobo** [comment]
Hi,
no worries. I thought about creating one, but it is not necessary. It is already integrated into the awesome ebook reader app "koreader". (https://github.com/koreader/koreader/wiki/Wallabag)
To install it see https://github.com/koreader/koreader/wiki/Installation-on-PocketBook-devices.
Bests :)

**Comment by wojtek1171** [comment]
I use koreader but couldn't get it to work with wallabag on my PB 626. Maybe the problem is on my server's side, I'll give it one more shot.
BTW I tried your nextcloud client and it works on PB 626 so you can add it to readme if you like. Thanks for your work. The thread can be closed ;)
